language: java
sudo: false
dist: trusty
jdk: oraclejdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - echo http://localhost:14563 >> ~/.java/deployment/security/exception.sites
install:
  - mvn clean package -Dmaven.test.skip=true
script:
  - mvn clean verify
