Sources
=======

Code is organized according to the Maven convention in `src/main/java` and
`src/test/java`. 


Building
========

RemoteSwingLibrary uses Apache Maven_ as a build tool.

__ http://maven.apache.org/

- `mvn clean package` packages RemoteSwingLibrary with dependencies.

- `mvn clean verify` run acceptance tests

Releasing
=========

- 


