Sources
=======

Code is organized according to the Maven convention in `src/main/java` and
`src/test/java`. 


Building
========

RemoteSwingLibrary uses Apache Maven as a build tool.

- `mvn clean package` packages RemoteSwingLibrary with dependencies.

- `mvn clean verify` run acceptance tests


Testing
=======

Run ``python run_atest.py --help`` to find what options for testing are possible.


Releasing
=========

- update library version to x.x.x in pom.xml
- run tests ``mvn clean verify``
- ``git commit -m "version to x.x.x" pom.xml``
- generate the html documentation: ``PYTHONPATH=target/remoteswinglibrary-x.x.x.jar python -m robot.libdoc RemoteSwingLibrary RemoteSwingLibrary-x.x.x.html``
- generate the xml documentation: ``PYTHONPATH=target/remoteswinglibrary-x.x.x.jar python -m robot.libdoc RemoteSwingLibrary RemoteSwingLibrary-x.x.x.xml``
- create tag ``git tag -a x.x.x``
- push ``git push`` and ``git push --tags``
- create a new release and upload the jar file and html documentation to https://github.com/robotframework/remoteswinglibrary/releases
- upload to Maven Repository (see https://github.com/robotframework/SwingLibrary/blob/master/BUILD.rest for detailed instructions)



